# Generated by Django 6.0.4 on 2026-04-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partie_Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('partieC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BG.partie_comune')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BG.resident')),
            ],
        ),
    ]
