# Generated by Django 6.0.4 on 2026-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='partieC',
            field=models.CharField(choices=[('Ascenseur', 'Ascenseur'), ('Parking', 'Parking'), ('Escalier', 'Escalier'), ('Piscine', 'Piscine')], default='Ascenseur', max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='email',
            field=models.EmailField(default='wesh@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Partie_Comune',
        ),
    ]
