# Generated by Django 6.0.4 on 2026-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0002_alter_signalement_partiec_resident_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='mot_de_passe',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
