# Generated by Django 6.0.4 on 2026-04-24 13:23

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0003_resident_mot_de_passe'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='resident',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='prenom',
        ),
        migrations.AddField(
            model_name='resident',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='resident',
            name='first_name',
            field=models.CharField(default='bonjou', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='resident',
            name='last_name',
            field=models.CharField(default='bonsoir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='password',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='resident',
            name='username',
            field=models.CharField(default='Patate', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
