# Generated by Django 6.0.4 on 2026-04-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0004_alter_resident_options_alter_resident_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
