# Generated by Django 6.0.4 on 2026-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0006_alter_resident_email_alter_resident_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='state',
            field=models.CharField(choices=[('Résolu', 'Resolu'), ('En cours', 'Encours'), ('En Attente', 'Enattente')], default='En Attente', max_length=50),
        ),
    ]
