# Generated by Django 6.0.4 on 2026-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0007_signalement_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='description',
            field=models.CharField(default='typeshit', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signalement',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name=''),
        ),
    ]
