# Generated by Django 6.0.4 on 2026-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0008_signalement_description_alter_signalement_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='priorite',
            field=models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute')], default='Basse', max_length=50),
        ),
    ]
