# Generated by Django 6.0.4 on 2026-04-27 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0009_signalement_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
