# Generated by Django 6.0.4 on 2026-04-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0010_signalement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
