# Generated by Django 6.0.4 on 2026-04-29 20:01

import BG.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0011_signalement_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[BG.models.Validate_fichier], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
