# Generated by Django 6.0.4 on 2026-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0014_notification_created_at_alter_notification_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residence',
            field=models.CharField(default='B-12', max_length=50),
        ),
    ]
