# Generated by Django 6.0.4 on 2026-05-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0016_alter_resident_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalement',
            name='residence',
            field=models.CharField(blank=True, default='B-12', max_length=50, null=True),
        ),
    ]
