# Generated by Django 6.0.4 on 2026-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BG', '0018_notification_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalement',
            name='partieC',
            field=models.CharField(choices=[('Ascenseur', 'Ascenseur'), ('Parking', 'Parking'), ('Escalier', 'Escalier'), ('Piscine', 'Piscine'), ('Hall', 'Hall'), ('Jardin', 'Jardin'), ('Gym', 'Gym')], default='Ascenseur', max_length=50),
        ),
    ]
